### ISSUE TITLE
is it possible to make chatterino7 for linux be not an AppImage .. it kinda triggers me that its not an installable package

### ISSUE THREAD

**Issue by FourLineCode** [SevenTV/chatterino7#10]
**Describe your issue**

**Screenshots**

**OS and Chatterino Version**

**Comment by Mm2PL** [comment]
I'd just like to interject for a moment. What you're refering to as Linux, is in fact, (probably) GNU/Linux, or as I've recently taken to calling it, GNU plus Linux. Linux is not an operating system unto itself, but rather another free component of a fully functioning GNU system made useful by the GNU corelibs, shell utilities and vital system components comprising a full OS as defined by POSIX.

Also each distro is different and uses different package managers. :)

**Comment by zneix** [comment]
As mm2pl said, what really is "linux"? With so few details and not even specifying basic things such as distribution and the package manager you're using this issue is literally pointless.
Jokes aside though, upstream Chatterino is not in most common package managers anyway.
Please keep in mind that this fork lives since like only last Wednesday or so, so it's not like it will be immediately added to the pool of core Debian packages or whatever else.

As for the alternatives to AppImage:
1. You could try compiling from source, it's all [well documented](https://github.com/Chatterino/chatterino2/blob/master/BUILDING_ON_LINUX.md);
2. If you're an Arch Linux user, I'll be soon releasing an AUR package(s) for chatterino7, so stay tuned.

**Comment by zneix** [comment]
> 2. If you're an Arch Linux user, I'll be soon releasing an AUR package(s) for chatterino7, so stay tuned.

Update on this, the mentioned AUR package has been created 🎉 https://aur.archlinux.org/packages/chatterino2-7tv-git

**Comment by zneix** [comment]
Because of not providing any sort of necessary details and no compliance with issue template I'm going to close this issue as it makes no sense - it's not easy to package forks of software in every distro immidiatelly.
However, feel free to make a comment below with necessary details (like kernel version and distribution you're using and if packaging chatterino7 will be possible for the given distro, I'll consider reopening this.
