### ISSUE TITLE
mentions are shown twice used alongside with bttv extension ..

### ISSUE THREAD

**Issue by FourLineCode** [SevenTV/chatterino7#11]
i use 7tv extension along side with bttv extension because i need some of the settings bttv provides .. but mentions in chat are shown twice because of it .. i dont know if its because of bttv or not .. it might just be a 7tv extension bug

**Comment by zneix** [comment]
Could you provide a screenshot of duplicated mentions? I believe this has nothing to do with chatterino itself and might be rather an issue with seventv for web, not chatterino.

**Comment by zneix** [comment]
Because of no response I'll go ahead and close this issue as I believe you're talking about 7tv browser extension and not chatterino7 (you've mentioned "along side with bttv extension" and "a 7tv extension bug"). For issues about 7tv extensions, please open issues under [seventv/seventv](https://github.com/seventv/seventv/issues) issue tracker (what you've mentioned is a known issue though, so no need for reporting that).
