### ISSUE TITLE
Upstream has 7tv Support now - is this fork still recommended?

### ISSUE THREAD

**Issue by selvex** [SevenTV/chatterino7#173]
Have been using this awesome fork for a while, auto updating has not been working though which I think is normal because it's a fork.

When I did my manual updating today, I saw that the Chatterino base client added 7tv support now.

Does this mean this fork is obsolete now? I am not aware of other features this provides if there are any.

Wanted to ask if it is recommended to keep using this fork or the upstream.
Best regards.

### OS and Chatterino Version

7.3.5

**Comment by Felanbird** [comment]
The main branch of Chatterino2 does not have 7TV paints, 7TV animated profile pictures, or (coming soon ™️) 7TV personal emotes, and it never will. `(unless something crazy happens)`

So if you'd like to have any of these features, you should stay on chatterino7, otherwise you are free to swap back.

**Comment by AnatoleAM** [comment]
> and it never will

Regarding personal emotes and sub-extension emotes, I don't believe there will be a valid argument against their implementation, though it really is up to the maintainers if they wish to be stingy. In which case we will continue to maintain the fork and heavily promote it instead of the upstream.

**Comment by Felanbird** [comment]
> we will continue to maintain the fork 

That'll be the day 😁
