### ISSUE TITLE
No AppImage for v7.4.2?

### ISSUE THREAD

**Issue by markx86** [SevenTV/chatterino7#215]
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

There used to be an AppImage version of Chatterino7 on every new release, but I've noticed that the latest version (`v7.4.2` at the time of writing this) does not have one.  
After some digging, the build workflow for the AppImage seems to have been removed in the following commit fb2aab8cf2a30c37612939f12dda1fbc79699d44, however the build script for it (`.CI/CreateAppImage.sh`) still remains.  
Was this a little mistake, or has the AppImage version been discontinued (the upstream Chatterino2 still has the AppImage version, this is why I'm reporting this here).

### OS and Chatterino Version

Chatterino v7.4.1 on Fedora 37

**Comment by Nerixyz** [comment]
Upstream removed appimage builds on Ubuntu 22.04 in https://github.com/Chatterino/chatterino2/pull/4400. Since Chatterino7 doesn't build with Qt 5.12.12 (removed in https://github.com/SevenTV/chatterino7/pull/69), no appimage was built afterwards. It would be nice to still provide appimages, but given ["The AppImage from Ubuntu 22.04 is broken. Approach with caution"](https://github.com/Chatterino/chatterino2/blob/32499f0e0ecaa9b23ccd8e330d12c48d77029f29/.docker/README.md?plain=1#L31), this seems hard. If you have an idea on how to build an appimage on Ubuntu 22.04, feel free to make a PR upstream and it will get merged here.

**Comment by Nerixyz** [comment]
I've added an AppImage built on 22.04 to CI - it's now in the files for the [nightly release](https://github.com/SevenTV/chatterino7/releases/tag/nightly-build). It would be great if you could check whether it works!

**Comment by markx86** [comment]
I can confirm it works! Thanks!
