### ISSUE TITLE
Link Preview Not Displaying

### ISSUE THREAD

**Issue by IIIYummyIII** [SevenTV/chatterino7#22]
Link preview does not work. It's enabled but does not preview any image. It only shows the URL without displaying the image. 

![Screenshot 2021-06-25 211542](https://user-images.githubusercontent.com/86502975/123497268-8253c380-d5fa-11eb-9317-7c179399a67c.png)

![Untitled](https://user-images.githubusercontent.com/86502975/123497339-fee6a200-d5fa-11eb-8aca-25f5d962d5ae.png)

Windows 10, 7.3.3

**Comment by zneix** [comment]
This is not an issue on neither Chatterino7 or Chatterino2.
The server that provides you the tooltip information was tweaked, so it doesn't return thumbnails at all due to security reasons. That change is temporary and should be reverted once the server gets the security issue with thumbnails fixed.
