### ISSUE TITLE
Show when a 7tv emote is "aliased" in hover preview.

### ISSUE THREAD

**Issue by NotNotQuinn** [SevenTV/chatterino7#35]
**Describe your issue**

When you hover over an emote, it shows the emote name, author and provider. It would be nice to include information about a channel alias, if relevant, like the original name.

**Screenshots**

Original
![image](https://i.imgur.com/6y6nAkD.png)
Aliased
![image](https://i.imgur.com/jsN5PjA.png)

**OS and Chatterino Version**

Win 10
Chatterino Nightly 7.3.3 (commit 452da6bdd)

**Comment by goldbattle** [comment]
It doesn't look like this is something in the V2 api / doable currently.
It will currently show the aliased "name" but no details on the original name if it has been aliased.

For example:
- https://7tv.app/users/61da7024600369a98b38aa78
- https://api.7tv.app/v2/users/26775809/emotes
- turtoise -> Toise (turtoise will not be anywhere in the api response)
![image](https://user-images.githubusercontent.com/2222562/149059640-65153f93-ae2a-489f-bd0a-0183832d9e90.png)

Version 7.3.4.

It would be nice to have it reported as a `name_original` in the api. I don't that the V3 api will have this [shown anyplace](https://github.com/SevenTV/Common/blob/6cb0afe6738b01f936f603dc861b06e84ff0803d/structures/type.emote.go#L76-L105) (maybe @AnatoleAM can chime in on this).

Otherwise the only way to get this would be to do an API call for each emote using its id. For example:
https://api.7tv.app/v2/emotes/60e4410878cfe95e2d2e2d33

**Comment by Felanbird** [comment]
This was fixed at some point
![image](https://user-images.githubusercontent.com/41973452/203199414-a765a12e-1773-4cb9-bae6-0f45303ba192.png)
