### ISSUE TITLE
Some emojis and the emoji picker icon dont render on Pop OS 21.04

### ISSUE THREAD

**Issue by FourLineCode** [SevenTV/chatterino7#38]
![image](https://user-images.githubusercontent.com/56719270/128639985-3baffe95-9673-404d-97f9-5dee941b8a00.png)

Im using chatterino 7.3.4 AppImage on PopOS 21.04 .. it worked properly on ubuntu 20.04 ..

**Comment by zneix** [comment]
This looks like an issue with your font. As for the icon, you might be missing a qt package for svg formats / imgaeformats. I don't know how it's called exactly on Ubuntu / PopOS but you should be able to find something.
I'm gonna close this issue since it's not directly problem related to Chatterino nor this fork, but feel free to comment on this issue if you manage to fix the issue / find something about it.
