### ISSUE TITLE
Emotes are not rendered in recent messages

### ISSUE THREAD

**Issue by Meeeee6623** [SevenTV/chatterino7#6]
**Describe your issue**

When opening a new channel, or chatterino itself, 7TV emotes do not load and just display as text in historical messages. 

**Screenshot**

![image](https://user-images.githubusercontent.com/63178260/119915110-bff7fa80-bf2f-11eb-84bb-579e62b09cfa.png)

**OS and Chatterino Version**

Chatterino 7.3.2

**Comment by zneix** [comment]
This is a known upstream issue with bttv/ffz emotes not loading in message history provided by recent-messages. Perhaps we need to apply some extra logic to respect 7tv stuff on channel initialization. Edited your issue to be more specific about what is the problem here.

**Comment by zneix** [comment]
From my testing it looks like this is entirely a race condition - I made around 30 restarts with 1 split and in about ~25 of those emotes did load, because recent messages loaded faster than emotes from third party services (this doesn't affect 7tv only, but BTTV and FFZ as well).
I couldn't find an issue on upstream repository, but this has been an issue for ages. I'll make a proper issue and see if it's possible to even fix it in a reasonable way.
Closing for now, as this is an issue with upstream and isn't related to any features introduced in the fork.
